### ISSUE TITLE
Contribution and Information Sharing

### ISSUE THREAD

**Issue by lunarsoap5** [zeldaret/ph#1]
Hello, 

I had a couple questions about this project that I was hoping could be answered, when possible:

1. Are there any contribution guidelines/documentation? Meaning, if someone were to want to try their hand at decompiling a function, what steps would they have to go through to ensure that the code they write matches? 
2.  I am one of the developers for a randomizer of Phantom Hourglass and was wondering if you would be willing to share any documentation/information that you may have regarding functions, structs, etc. We would of course be willing to share resources that we have gathered as well over the course of our development. Our project supports the US version of the game, but maybe some of the info translates over. Here is a link to our repo if you would like to look at it: https://github.com/phst-randomizer/ph-randomizer

Thank you for your time and don't hesitate to reach out to me either on here or on discord (@lunarsoap) if you have any questions! :)

**Comment by AetiasHax** [comment]
Thanks for reaching out! Let me answer your questions:

1. No guidelines or documentation yet. This project is still rather new, so I haven't established any guidelines, even for myself lol. I'm currently making slow and steady progress by decompiling the inventory class. After I've finished doing so, I'll be more qualified to make guidelines and help others get started.
2. Very cool! I have no idea how I haven't seen the randomizer yet, so thanks for sharing! I'm absolutely willing to share any info with you and the other developers. I'll contact you via Discord and maybe we can talk more there?
